title: GuerrillaGrok
description: Papa. Soldier. Blue Team Benchwarmer.
include: 
 - _assets
 - _navigation
minima:
  skin: dark
header_pages:
 - _navigation/essays.md
 - _navigation/guides.md
 - _navigation/notes.md
 - _navigation/examples.md
 - _navigation/demos.md




