title: GuerrillaGrok
description: Papa. Soldier. Blue Team Benchwarmer.
include: _assets
theme: minima
minima:
  skin: dark
header_pages:
 - essays.md
 - notes.md
 - guides.md
 - examples.md
 - demos.md
