title: GuerrillaGrok
description: Papa. Soldier. Blue Team Benchwarmer.
include: 
 - _assets
 - _navigation
theme: minima
minima:
  skin: solarized-dark
header_pages:
 - essays.md
 - _navigation/notes.md
 - guides.md
 - examples.md
 - demos.md
