title: GuerrillaGrok
description: Papa. Soldier. Blue Team Benchwarmer.
include: 
 - _assets
 - _navigation
theme: minima
minima:
  skin: solarized-dark
header_pages:
 - _navigation/demos.md
 - _navigation/essays.md
 - _navigation/examples.md
 - _navigation/guides.md
 - _navigation/notes.md



